# crear imagen de mongodb
version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./dbdata:/data/db
      # - mongodb_data:/data/db
    networks:
      - mongodb
  app:
    build: .
    container_name: app
    ports:
      - "5000:5000"
    depends_on:                   # depende de mongodb para que se ejecute
      - mongodb
    networks:
      - mongodb      # se conecta a la red mongodb
    volumes:
      - ./src:/app/src        

networks:
  mongodb:
    driver: bridge

# volumes:
#   mongodb_data:
