# crear imagen de mongodb
version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb
  node:
    build: .
    container_name: node
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - mongodb

networks:
  mongodb:
    driver: bridge

volumes:
  mongodb_data:
