FROM node 


# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json ./

RUN npm install

# Bundle app source
COPY ./src ./src
# COPY ./app.js .

# Expose the port the app runs on
EXPOSE 5001

RUN npx prisma init

COPY prisma ./prisma

COPY .env .
# RUN npx prisma migrate dev --name init
RUN npx prisma generate

# RUN npx prisma migrate status

# Serve the app
# CMD ["prisma","generate","npm", "run","start"]
 # este comando corre las migraciones y el servidor
# CMD ["npm", "run","dev"]  
# este comando corre el servidor
CMD ["npm", "run","start"]   


# Docker
# docker build . -t users-barfinder360
# Docker run users-barfinder360
# docker run -d -p 5001:5001 --name users-barfinder360 users-barfinder360   // este comando es para correr el contenedor de docker

# este comando es para correr el contenedor de docker con el init
# docker run -p 5001:5001 --init --rm --name users-barfinder360 users-barfinder360 

# docker-compose
# docker-compose up --build

# este codigo es para crear la imagen de docker y -t es para darle un nombre a la imagen
# docker build . -t users-micro

