FROM node 


# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json .

RUN npm install

# Bundle app source
COPY /src /src

# Expose the port the app runs on
EXPOSE 5001

# Serve the app
CMD ["npm", "start"]

