version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=barfinder
    ports:
      - "5433:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  users_barfinder360:
    container_name: users_barfinder360
    restart: always
    build: .
    environment:
      - PORT=5001
    ports:
      - '5001:5001'
    depends_on:
      - postgres

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - '8080:8080'
    depends_on:
      - postgres

      
# este comando es para correr el contenedor de docker con el init
# docker run -p 5001:5001 --init --rm --name users-barfinder360 users-barfinder360 

# docker-compose
# docker-compose up --build